name: Auto Deploy to GitHub Pages
on:
  push:
    branches: [ main ]  # 触发分支（与您的开发分支同名）

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 这样GITHUB_TOKEN就有写仓库的权限了
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # 与您本地环境一致

      - name: Install dependencies
        run: yarn install   # 或 npm install

      - name: Build site
        run: yarn build     # 执行 Docusaurus 构建命令

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用内置 Token，无需额外配置[2](@ref)
          # 若仍失败，增加权限声明
          publish_branch: gh-pages   # 显式指定目标分支
          publish_dir: ./build       # 构建输出目录
          keep_files: false          # 清理旧文件